script.run_in_callback(function()
    while true do
        ScriptGlobal(4538671):set_int(0)
        ScriptGlobal(262146):set_float(0)
        script.yield(0)
    end
end)
-- MONEY FRONTS CAREER PROGRESS & SCRIPT - ImagineNothing
-- EVERYTHING ELSE* FOUND BY ShinyWasabi
script.run_in_callback(function()
    local is_online = ScriptGlobal(2655293)
    if is_online:get_int() ~= -1 then
        notify.info("Script - Career Progress", "Completing challenges...")
        stats.set_packed_bool(54653, true)
        stats.set_int("MPX_SB_CAR_WASH_OWNED", 1)
        stats.set_int("MPX_SB_HELI_TOURS_OWNED", 1)
        stats.set_int("MPX_SB_WEED_SHOP_OWNED", 1)
        stats.set_packed_bool_range(28313, 28318, true)
        stats.set_packed_int(24928, 10, true)
        stats.set_int("MPX_PROG_HUB_TYCOON25_EARNINGS", 2000000, true)
        stats.set_int("MPX_PROG_HUB_CWASH_SAFEEARNINGS", 500000, true)
        stats.set_packed_bool_range(51278, 51280, true)
        stats.set_packed_bool_range(51285, 51297, true)
        stats.set_int("MPX_PROG_HUB_MFH_EARNINGS", 5000000, true)
        stats.set_packed_bool_range(28272, 28287, true)
        stats.set_int("MPX_PROG_HUB_CBR_EARNINGS", 5000000, true)
        stats.set_int("MPX_SUM23_AVOP_PROGRESS", 4095, true)
        stats.set_int("MPX_ULP_MISSION_PROGRESS", 16383)
        stats.set_int("MPX_YACHT_MISSION_FLOW", 21845)
        stats.set_packed_bool_range(41507, 42022, true)
        stats.set_int("MPX_HACKER_DEN_OWNED", 1, true)
        stats.set_packed_bool(9539, true)
        stats.set_packed_int(24903, 25)
        stats.set_packed_int(24904, 2)
        stats.set_int("MPX_PROG_HUB_DEN24_SAFEEARNINGS", 100000, true)
        stats.set_int("MPX_HACKER24_GEN_BS", 8160, true)
        stats.set_packed_bool(9549, true)
        stats.set_packed_bool_range(9542, 9546, true)
        stats.set_int("MPX_BAIL_OFFICE_OWNED", 1, true)
        stats.set_packed_bool(9537, true)
        stats.set_packed_bool(7639, true)
        stats.set_packed_int(7669, 5)
        stats.set_packed_int(7672, 2)
        stats.set_int("MPX_PROG_HUB_BOUNTY_EARNINGS", 5000000, true)
        stats.set_packed_int(7670, 10)
        stats.set_packed_int(7674, 3)
        stats.set_packed_int(7671, 25)
        stats.set_int("MPX_PROG_HUB_BOUNTIES_ALIVE_BS", -1, true)
        stats.set_int("MPX_BAIL_PROPERTY_EARNINGS", 1000000, true)
        stats.set_int("MPX_SALVAGE_YARD_OWNED", 1, true)
        stats.set_packed_bool_range(42037, 42038, true)
        stats.set_packed_bool_range(42041, 42042, true)
        stats.set_packed_bool_range(42044, 42051, true)
        stats.set_int("MPX_PROG_HUB_SALV23_EARN_SALV", 2500000, true)
        stats.set_int("MPX_PROG_HUB_SALV23_EARN_PERF", 5, true)
        stats.set_int("MPX_PROG_HUB_SALV23_EARN_SELL", 10000000, true)
        stats.set_int("MPX_XM22_MISSIONS_SA", -1, true)
        stats.set_int("MPX_LFETIME_BIKER_BUY_COMPLET6", 100, true)
        stats.set_int("MPX_XM22_FLOW", -1, true)
        stats.set_int("MPX_LIFETIME_BKR_SELL_EARNINGS6", 10000000, true)
        stats.set_int("MPX_LFETIME_BIKER_SELL_COMPLET6", 10, true)
        stats.set_packed_int(41241, 5)
        stats.set_int("MPX_PROG_HUB_LSDW_FJ_NO_DEATHS", 25, true)
        stats.set_int("MPX_PROG_HUB_DAX_CLONE_KILLS", 100, true)
        stats.set_packed_bool_range(41660, 41670, true)
        stats.set_packed_bool(28257, true)
        stats.set_int("MPX_FIXER_COUNT", 100, true)
        stats.set_int("MPX_FIXER_GENERAL_BS", -1, true)
        stats.set_bool("MPX_AWD_PARTY_NIGHT", true)
        stats.set_bool("MPX_AWD_BILLIONAIRE_GAMES", true)
        stats.set_bool("MPX_AWD_HOOD_PASS", true)
        stats.set_int("MPX_AWD_COLD_CALLER", 10, true)
        stats.set_int("MPX_PROG_HUB_FXER_PAY_HIT_BONUS", 100, true)
        stats.set_bool("MPX_AWD_SHORTFRANK_1", true)
        stats.set_bool("MPX_AWD_SHORTFRANK_2", true)
        stats.set_bool("MPX_AWD_SHORTFRANK_3", true)
        stats.set_bool("MPX_AWD_SHORTLAMAR_1", true)
        stats.set_bool("MPX_AWD_SHORTLAMAR_2", true)
        stats.set_bool("MPX_AWD_SHORTLAMAR_3", true)
        stats.set_int("MPX_PROG_HUB_FIXER_SEC_CON_SPEC", 100, true)
        stats.set_int("MPX_FIXER_EARNINGS", 5000000, true)
        stats.set_packed_bool(22067, true)
        stats.set_int("MPX_NIGHTCLUB_JOBS_DONE", 25, true)
        stats.set_int("MPX_PROG_HUB_DANCE_DUR", 5, true)
        stats.set_packed_bool(15533, true)
        stats.set_packed_bool_range(22082, 22083, true)
        stats.set_packed_bool(36944, true)
        stats.set_packed_bool(41989, true)
        stats.set_int("MPX_NIGHTCLUB_VIP_APPEAR", 25, true)
        stats.set_int("MPX_PROG_HUB_NCLUB_POP_MAX_TME", 600, true)
        stats.set_int("MPX_HUB_EARNINGS", 50000000, true)
        stats.set_packed_bool(15966, true)
        stats.set_int("MPX_LFETIME_HANGAR_BUY_COMPLET", 100, true)
        stats.set_packed_bool(41676, true)
        stats.set_int("MPX_LFETIME_HANGAR_SEL_COMPLET", 1, true)
        stats.set_packed_bool(41987, true)
        stats.set_int("MPX_PROG_HUB_SMUGGLER_CRATES", 1000, true)
        stats.set_packed_bool_range(36924, 36938, true)
        stats.set_int("MPX_LFETIME_HANGAR_EARNINGS", 50000000, true)
        stats.set_int("MPX_FACTORYSETUP5", 1, true)
        stats.set_int("MPX_LFETIME_BIKER_BUY_COMPLET5", 2, true)
        stats.set_packed_int(9359, 25)
        stats.set_packed_bool_range(36870, 36917, true)
        stats.set_int("MPX_WVM_FLOW_BITSET_MISSIONS0", 1, true)
        stats.set_int("MPX_LIFETIME_BKR_SEL_COMPLETBC5", 1, true)
        stats.set_int("MPX_LFETIME_BIKER_SELL_COMPLET5", 1, true)
        stats.set_int("MPX_SR_WEAPON_BIT_SET", -1, true)
        stats.set_int("MPX_LFETIME_BIKER_BUY_COMPLET5", 25, true)
        stats.set_packed_bool_range(42002, 42013, true)
        stats.set_packed_bool_range(36831, 36865, true)
        stats.set_int("MPX_LIFETIME_BKR_SELL_EARNINGS5", 25000000, true)
        stats.set_int("MPX_OWNED_IE_WAREHOUSE", 1, true)
        stats.set_int("MPX_LFETIME_IE_EXPORT_COMPLETED", 25, true)
        stats.set_packed_bool_range(42029, 42036, true)
        stats.set_packed_bool_range(41874, 41883, true)
        stats.set_int("MPX_PROG_HUB_VEH_CARGO_SELL_PER", 50, true)
        stats.set_int("MPX_PROG_HUB_VEH_CARGO_SPECIAL", 5, true)
        stats.set_packed_bool(41988, true)
        stats.set_int("MPX_LFETIME_IE_MISSION_EARNINGS", 25000000, true)
        stats.set_int("MPX_LIFETIME_BKR_SELL_COMPLETBC", 1, true)
        stats.set_int("MPX_LIFETIME_BKR_SEL_COMPLETBC1", 1, true)
        stats.set_int("MPX_LIFETIME_BKR_SEL_COMPLETBC2", 1, true)
        stats.set_int("MPX_LIFETIME_BKR_SEL_COMPLETBC3", 1, true)
        stats.set_int("MPX_LIFETIME_BKR_SEL_COMPLETBC4", 1, true)
        stats.set_int("MPX_BAR_RESUPPLY_CR", 10, true)
        stats.set_int("MPX_LIFETIME_BKR_SELL_EARNINGS0", 25000000, true)
        stats.set_int("MPX_PROG_HUB_BIK_CUST_DEL_CASH", 2500000, true)
        stats.set_int("MPX_PROG_HUB_CLBH_BAR_EARNINGS", 500000, true)
        stats.set_int("MPX_PROG_HUB_BIK_CONTRACT_COUNT", 50, true)
        stats.set_packed_bool_range(7553, 7592, true)
        stats.set_int("MPX_WARHOUSESLOT0", 1, true)
        stats.set_int("MPX_LIFETIME_BUY_COMPLETE", 1, true)
        stats.set_int("MPX_PROG_HUB_FAIFAF_CRATES_COL", 250, true)
        stats.set_int("MPX_LIFETIME_CONTRA_EARNINGS", 50000000, true)
        stats.set_int("MPX_CAR_CLUB_MEMBERSHIP", 1, true)
        stats.set_packed_bool(31737, true)
        stats.set_packed_bool(31753, true)
        stats.set_bool("MPX_AWD_PRO_CAR_EXPORT", true)
        stats.set_int("MPX_TUNER_COMP_BS", 255)
        stats.set_int("MPX_AWD_AUTO_SHOP", 10, true)
        stats.set_int("MPX_AWD_CAR_CLUB_MEM", 100, true)
        stats.set_packed_bool_range(32397, 32399, true)
        stats.set_int("MPX_TUNER_COUNT", 25, true)
        stats.set_int("MPX_PROG_HUB_TUNER_CUS_DEL_CASH", 5000000, true)
        stats.set_packed_bool_range(27089, 27090, true)
        stats.set_int("MPX_VCM_FLOW_PROGRESS", -1, true)
        stats.set_int("MPX_AWD_ODD_JOBS", 100, true)
        stats.set_packed_bool(30309, true)
        stats.set_packed_bool(30522, true)
        stats.set_int("MPX_H4_MISSIONS", -1, true)
        stats.set_int("MPX_H4_PROGRESS", -1, true)
        stats.set_int("MPX_H4_H4_DJ_MISSIONS", 127)
        stats.set_int("MPX_AWD_TREASURE_HUNTER", 10, true)
        stats.set_int("MPX_PROG_HUB_CAYO_PRP_NO_DEATHS", 25, true)
        stats.set_int("MPX_CR_SUBMARINE", 1, true)
        stats.set_int("MPX_CR_STRATEGIC_BOMBER", 1, true)
        stats.set_int("MPX_CR_SMUGGLER_PLANE", 1, true)
        stats.set_int("MPX_CR_STEALTH_HELI", 1, true)
        stats.set_int("MPX_CR_PATROL_BOAT", 1, true)
        stats.set_int("MPX_CR_SMUGGLER_BOAT", 1, true)
        stats.set_int("MPX_PROG_HUB_CAYO_H_EARNINGS", 50000000, true)
        stats.set_int("MPX_CAS_HEIST_FLOW", -1, true)
        stats.set_packed_bool(28270, true)
        stats.set_packed_bool(36842, true)
        stats.set_int("MPX_AWD_PREPARATION", 25, true)
        stats.set_bool("MPX_AWD_CREWEDUP", true)
        stats.set_packed_bool(42025, true)
        stats.set_int("MPX_PROG_HUB_CASINO_H_EARNINGS", 50000000, true)
        stats.set_int("MPX_AWD_DAICASHCRAB", 100000, true)
        stats.set_packed_bool(18139, true)
        stats.set_packed_bool(36861, true)
        stats.set_int("MPX_GANGOPS_FLOW_BITSET_MISS0", -1, true)
        stats.set_packed_bool_range(41712, 41714, true)
        stats.set_int("MPX_PROG_HUB_DOOM_PRP_NO_DEATHS", 14, true)
        stats.set_int("MPX_PROG_HUB_DOOMSDAY_ACTS", 15, true)
        stats.set_packed_bool_range(36867, 36868, true)
        stats.set_packed_bool_range(41715, 41719, true)
        stats.set_packed_int(42100, 5)
        stats.set_int("MPX_PROG_HUB_HEIST_EARNINGS", 50000000, true)
        stats.set_packed_bool(42000, true)
        stats.set_packed_bool(25009, true)
        stats.set_packed_int(22063, 20)
        stats.set_int("MPX_ARENAWARS_AP_TIER", 50, true)
        stats.set_packed_int(42000, 20)
        stats.set_packed_bool(51339, true)
        stats.set_packed_bool(36840, true)
        stats.set_int("MPX_PROG_HUB_ADV_WINS", 50, true)
        stats.set_int("MPX_PROG_HUB_SURVIVALS_PLAYED", 1, true)
        stats.set_int("MPX_PROG_HUB_SURV_WAVES", 50, true)
        stats.set_int("MPX_AWD_FMHORDWAVESSURVIVE", 10, true)
        stats.set_packed_bool_range(41331, 41506, true)
        stats.set_int("MPX_PROG_HUB_SURV_WAVES", 250, true)
        stats.set_packed_bool(42023, true)
        stats.set_int("MPX_RACES_WON", 50, true)
        stats.set_int("MPX_PROG_HUB_T_TRIAL_PAR_TIME", -1, true)
        stats.set_int("MPX_PROG_HUB_T_TRL_PAR_TIME_RC", -1, true)
        stats.set_int("MPX_PROG_HUB_T_TRL_PAR_TIME_HSW", -1, true)
        stats.set_int("MPX_PROG_HUB_T_TRL_PAR_TIME_BKE", -1, true)
        stats.set_packed_int(41246, 20)
        stats.set_int("MPX_PROG_HUB_FST_LPS_RSTAR_RAC", 50, true)
        stats.set_int("MPX_DM_END", 1, true)
        stats.set_int("MPX_PROG_HUB_DM_TDM_PLAYS", 1, true)
        stats.set_int("MPX_AWD_FM_DM_WINS", 50, true)
        stats.set_int("MPX_PROG_HUB_DM_COMMUNITY_PLAYS", 10, true)
        stats.set_int("MPX_PROG_HUB_DTHM_KILL_5_WO_DIE", 25, true)
        stats.set_packed_bool(36922, true)
        stats.set_packed_int(42092, 5)
        stats.set_int("MPX_HUB_VEH_ENTH_OWNED_VEHS", 99, true)
        stats.set_int("MPX_VEHICLES_CUSTOMISED", 50, true)
        stats.set_packed_bool_range(36920, 36922, true)
        stats.set_int("MPX_PROG_HUB_WEAP_TYPE_ANSR", -1, true)
        stats.set_packed_int(41242, 255)
        stats.set_packed_bool_range(36941, 36942, true)
        stats.set_int("MPX_PROG_HUB_10_CHAL_ANSR", 10, true)
        stats.set_packed_bool_range(15456, 15460, true)
        script.yield(5000) -- pause before completing platinum awards challenges so we don't need to run the script again
        stats.set_packed_int(24929, 14)
        stats.set_packed_int(24905, 9)
        stats.set_packed_int(26809, 10)
        stats.set_packed_int(51052, 10)
        stats.set_packed_int(42084, 24)
        stats.set_packed_int(42085, 10)
        stats.set_packed_int(42089, 8)
        stats.set_packed_int(30226, 10)
        stats.set_packed_int(42093, 11)
        stats.set_packed_int(42094, 15)
        stats.set_packed_int(42086, 15)
        stats.set_packed_int(42087, 10)
        stats.set_packed_int(42090, 15)
        stats.set_packed_int(42088, 15)
        stats.set_packed_int(42091, 10)
        notify.success("Career Progress - Success!", "Please check your Career page.")
    else
        notify.info("Script - Career Progress", "Please join any freemode session and reload the script.")
    end
end)
